// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "mdnsSearchTime": {
        "en": "mDns search time for zeptrion devices in seconds",
        "de": "mDns Suchzeit für Zeptrion Geräte in Sekunden"
    },
    "zeptrionBlindMoveTime": {
        "en": "move blind and stop after time (t)",
        "de": "Storen move Zeit in Millisekunden"
    },
    "zeptrionDimmerDimTime": {
        "en": "dim light and stop after time (t)",
        "de": "Dimmer dimm-Zeit in Millisekunden"
    },
    "save_words": {
        "en": "on save adapter restarts with new config immediately",
        "de": "Der Adapter startet mit den neuen Konfigurationen nach den Speichern sofort neu"
    },
    "new_browse": {
        "en": "start new device scan",
        "de": "Starte neuer Geräte-Suchlauf"
    },
    "update_switch_states": {
        "en": "Update all Switch State",
        "de": "Update alle Schalter Stati"
    },
    "reconnect_websockets": {
        "en": "Renew all Websockets connections",
        "de": "Alle Websockets neu initialisieren"
    }
};